"""Schema imports for property service"""

from app.schemas.search_schemas import (
    PropertyTypeFilter,
    SortOption,
    Currency,
    Coordinates,
    DateRange,
    GuestCapacity,
    PriceRange,
    BasicSearchRequest,
    AdvancedFilters,
    AdvancedSearchRequest,
    LocationSuggestionsRequest,
    AvailabilityRequest,
    SavedSearchRequest,
    TrendingPropertiesRequest,
    NearbyPropertiesRequest,
    SearchFeedbackRequest,
    PaginationMeta,
    SearchMetadata,
    BaseResponse,
    ErrorResponse,
)

from app.schemas.property_schemas import (
    AmenityResponse,
    PropertyImageResponse,
    ReviewSummary,
    HostInfo,
    PricingInfo,
    PropertySearchResult,
    PropertyDetailResponse,
    PropertySearchResponse,
    LocationSuggestion,
    LocationSuggestionsResponse,
    AvailabilityResponse,
    SavedSearchResponse,
    SavedSearchesResponse,
    TrendingProperty,
    TrendingPropertiesResponse,
    NearbyPropertiesResponse,
    SearchAnalytics,
    SearchAnalyticsResponse,
    SearchErrorResponse,
    SearchFeedbackResponse,
    HealthCheckResponse,
)

__all__ = [
    # Search request schemas
    "PropertyTypeFilter",
    "SortOption", 
    "Currency",
    "Coordinates",
    "DateRange",
    "GuestCapacity",
    "PriceRange",
    "BasicSearchRequest",
    "AdvancedFilters",
    "AdvancedSearchRequest",
    "LocationSuggestionsRequest",
    "AvailabilityRequest",
    "SavedSearchRequest",
    "TrendingPropertiesRequest",
    "NearbyPropertiesRequest",
    "SearchFeedbackRequest",
    
    # Response schemas
    "AmenityResponse",
    "PropertyImageResponse",
    "ReviewSummary",
    "HostInfo",
    "PricingInfo",
    "PropertySearchResult",
    "PropertyDetailResponse",
    "PropertySearchResponse",
    "LocationSuggestion",
    "LocationSuggestionsResponse",
    "AvailabilityResponse",
    "SavedSearchResponse",
    "SavedSearchesResponse",
    "TrendingProperty",
    "TrendingPropertiesResponse",
    "NearbyPropertiesResponse",
    "SearchAnalytics",
    "SearchAnalyticsResponse",
    "SearchErrorResponse",
    "SearchFeedbackResponse",
    "HealthCheckResponse",
    
    # Utility schemas
    "PaginationMeta",
    "SearchMetadata", 
    "BaseResponse",
    "ErrorResponse",
]