"""
AI service models package.
"""
from .database import (
    Base,
    Conversation,
    ChatMessage,
    VoiceTranscription,
    VoiceSynthesis,
    AIPreferences,
    UserContext,
    ConversationAnalytics,
    FunctionCall,
    AISuggestion,
    ConversationEmbedding,
)
from .schemas import (
    MessageType,
    ConversationStatus,
    IntentType,
    VoiceGender,
    Language,
    ChatMessage as ChatMessageSchema,
    ChatMessageCreate,
    ChatMessageResponse,
    Conversation as ConversationSchema,
    ConversationCreate,
    ConversationWithMessages,
    VoiceTranscription as VoiceTranscriptionSchema,
    VoiceTranscriptionRequest,
    VoiceSynthesis as VoiceSynthesisSchema,
    VoiceSynthesisRequest,
    AIPreferences as AIPreferencesSchema,
    AIPreferencesUpdate,
    UserContext as UserContextSchema,
    ConversationAnalytics as ConversationAnalyticsSchema,
    FunctionCall as FunctionCallSchema,
    ActionExecution,
    ActionResult,
    AISuggestion as AISuggestionSchema,
    SuggestionRequest,
    WebSocketMessage,
    TypingIndicator,
    StandardResponse,
    ErrorResponse,
)

__all__ = [
    # Database models
    "Base",
    "Conversation",
    "ChatMessage",
    "VoiceTranscription",
    "VoiceSynthesis",
    "AIPreferences",
    "UserContext",
    "ConversationAnalytics",
    "FunctionCall",
    "AISuggestion",
    "ConversationEmbedding",
    
    # Enums
    "MessageType",
    "ConversationStatus",
    "IntentType",
    "VoiceGender",
    "Language",
    
    # Schemas
    "ChatMessageSchema",
    "ChatMessageCreate",
    "ChatMessageResponse",
    "ConversationSchema",
    "ConversationCreate",
    "ConversationWithMessages",
    "VoiceTranscriptionSchema",
    "VoiceTranscriptionRequest",
    "VoiceSynthesisSchema",
    "VoiceSynthesisRequest",
    "AIPreferencesSchema",
    "AIPreferencesUpdate",
    "UserContextSchema",
    "ConversationAnalyticsSchema",
    "FunctionCallSchema",
    "ActionExecution",
    "ActionResult",
    "AISuggestionSchema",
    "SuggestionRequest",
    "WebSocketMessage",
    "TypingIndicator",
    "StandardResponse",
    "ErrorResponse",
]